### ISSUE TITLE
[Bug] - Getting Exception in BotService When Calling UCI-APIs

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/orchestrator#44]
BotService we are using to get bot details and update user details throw UCI-API. We need to figure out where and why this issue getting on the backend side.

**Exception**
- [ ] com.uci.utils.BotService: Error in getting bot: Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
- [ ] com.uci.utils.BotService: Error in updating user: readAddress(..) failed: Connection reset by peer; nested exception is io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

**Comment by karntrehan** [comment]
@pankajjangid05 to check current numbers and update.

**Comment by pankajjangid05** [comment]
- Today we triggered the notification for 82717 users and got this "error : readAddress(..) failed: Connection reset by peer" 22 times, this is a web client error.
- Not getting this error "Connection prematurely closed BEFORE response"

**Comment by pankajjangid05** [comment]
For the first issue com.uci.utils.BotService: Error in getting bot: Connection prematurely closed BEFORE response

I have encountered cache issues while making multiple calls to the Bot services (UCI-APIs) using a web client. To address this problem, I have implemented some logic. I plan to deploy the updated version on the staging environment and perform thorough testing.

**Comment by chinmoy12c** [comment]
@pankajjangid05 to check if the problem persists on prod environment.

**Comment by pankajjangid05** [comment]
Not getting again on prod and staging while sending 100005 notifications.
