### ISSUE TITLE
[Bug] Duplication of Kafka topics from Orchestrator

### ISSUE THREAD

**Issue by susheelvar** [samagra-comms/orchestrator#58]
We are currently encountering issues with the orchestrator while attempting to send notifications. The problem arises from the orchestrator service consuming Kafka topics multiple times, resulting in duplicated notifications being sent to our users by the subsequent service.

To address this, we should focus on the following steps:

1. Clean up the [code](https://github.com/samagra-comms/orchestrator/blob/master/src/main/java/com/uci/orchestrator/Consumer/ReactiveConsumer.java#L107) involved in the process.
2. Separate the flow of notifications and ODK forms to allow for better identification and troubleshooting of the issues at hand.

**Comment by pankajjangid05** [comment]
We resolved the duplication issue within Kafka topics by using a hacky solution(rejected duplicate IDs by using in-memory DS). Currently, we need to solve this issue using a proper and permanent method.

During our last debugging, we were able to use manual ack to reduce the duplicates in Kafka, the numbers went down from approx 600 extra to 200 extra
We still need to accurately fix this to prevent any extra in the topic.

**Comment by karntrehan** [comment]
To move to a redis handling to ensure deduplication along with working on a longer fix.

**Comment by pankajjangid05** [comment]
I implemented Redis in the orchestrator to consume topics. Firstly, we check if the topic exists in Redis. If it does, we ignore that topic and move on to consume the next one.

[git commit link](https://github.com/samagra-comms/orchestrator/commit/d86aaae48b769efb5ea7f4bad023e12feaea77c3)
